version: '3.8'

services:
  emqx:
    image: emqx:5.0
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node.emqx.io
    networks:
      - platform

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.8'
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=
      - ZOO_CLIENT_USER=
      - ZOO_CLIENT_PASSWORD=
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - platform

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.4'
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
    networks:
      - platform

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-cluster
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - platform

networks:
  platform:
    driver: bridge
