version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=
      - ZOO_CLIENT_USER=
      - ZOO_CLIENT_PASSWORD=
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - platform

  kafka:
    image: 'bitnami/kafka:3.4'
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
    networks:
      - platform

networks:
  platform:
