version: '3.8'

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:6.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    networks:
      - platform

  redis:
    container_name: redis
    image: bitnami/redis:7.0
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - platform

  minio:
    container_name: minio
    image: bitnami/minio:2023.4.20
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - platform

  cassandra:
    container_name: cassandra
    image: 'bitnami/cassandra:4.1'
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD_SEEDER=
    networks:
      - platform

  influx:
    container_name: influx
    image: bitnami/influxdb:2.7
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=
      - INFLUXDB_USER=
      - INFLUXDB_USER_PASSWORD=
      - INFLUXDB_DB=
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    networks:
      - platform

  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - platform

networks:
  platform:
    driver: bridge
