version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.7.0
    ports:
      - 9200:9200  
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - platform

  kibana:
    image: bitnami/kibana:8.7.0
    ports:
      - 5601:5601
    environment:
    - KIBANA_ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - platform

networks:
  platform:
