version: '3.8'

services:
  mongo:
    image: bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    networks:
      - platform

  redis:
    image: bitnami/redis:7.0
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - platform

  minio:
    image: bitnami/minio:2023.4.20
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - platform

  cassandra:
    image: 'bitnami/cassandra:4.1'
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_PASSWORD=
      - CASSANDRA_USERNAME=
      - CASSANDRA_PASSWORD_SEEDER=
    networks:
      - platform

  influx:
    image: bitnami/influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=
      - INFLUXDB_USER=
      - INFLUXDB_USER_PASSWORD=
      - INFLUXDB_DB=
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    networks:
      - platform

networks:
  platform:
