version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:15
    container_name: postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
    networks:
      - platform

  sonarqube:
    image: bitnami/sonarqube:10
    container_name: sonarqube
    ports:
      - '9000:9000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
    depends_on:
      - postgresql
    networks:
      - platform

networks:
  platform:
    driver: bridge
